#!/usr/bin/env bash

source "${HOME}"/dotfiles/path_exports.bash

# Commands that should be applied only for interactive shells.
[[ $- == *i* ]] || return

shopt -s checkwinsize
shopt -s extglob
shopt -s globstar
shopt -s checkjobs

source "${HOME}"/dotfiles/berquist.bash-theme
source "${HOME}"/dotfiles/aliases.bash
source "${HOME}"/dotfiles/history.bash
source "${HOME}"/dotfiles/interactive_exports.bash
source "${HOME}"/dotfiles/functions.bash

GPG_TTY="$(tty)"
export GPG_TTY
