#!/usr/bin/env bash

# include ~/.profile if it exists
[[ -f ~/.profile ]] && source ~/.profile

# include ~/.bashrc if it exists
[[ -f ~/.bashrc ]] && source ~/.bashrc

{%@@ if profile == "osmium" @@%}
{%@@ else @@%}
export PS1='\u@\h:\w
\$ '

export SCRATCH=/scratch
export HOME1=/dftman/home1/ericb
export HOME2=/dftman/home2/ericb
export VAGRANT_HOME="${HOME2}"/vagrant

if [[ "${HOSTNAME}" == "coreman4" ]]; then
    export PYENV_ROOT="${HOME2}/pyenv"
    spack_base="${HOME2}"/spack
elif [[ "${HOSTNAME}" == "cheetah" ]]; then
    spack_base="${HOME2}"/spack_cheetah
elif [[ "${HOSTNAME}" == "dellman4" ]]; then
    export PYENV_ROOT="${HOME2}/pyenv_dellman4"
    spack_base="${HOME2}"/spack_dellman4
elif [[ "${HOSTNAME}" == "dellman5" ]]; then
    spack_base="${HOME2}"/spack_dellman5
elif [[ "${HOSTNAME}" == "gpuman2.q-chem.com" ]]; then
    spack_base="${HOME2}"/spack_gpuman2
elif [[ "${HOSTNAME}" == "epycman1" ]]; then
    spack_base="${HOME2}"/spack_epycman
fi

[[ -d "${PYENV_ROOT}/bin" ]] && export PATH="${PYENV_ROOT}/bin:${PATH}"
if command -v pyenv >/dev/null 2>&1; then
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
fi
if command -v pyenv-virtualenv-init 1>/dev/null 2>&1; then eval "$(pyenv virtualenv-init -)"; fi

[[ -d "${spack_base}" ]] && source "${spack_base}"/share/spack/setup-env.sh

[[ -f "${HOME}/.bashrc" ]] && source "${HOME}/.bashrc"

# Rust
[[ -f "${HOME}/.cargo/env" ]] && source "${HOME}/.cargo/env"

module use "${HOME}"/modules/work
if [[ "${HOSTNAME}" == "coreman4" ]]; then
    module use "${HOME}"/modules/coreman4
fi

nix_sh=/dftman/home/ericb/.nix-profile/etc/profile.d/nix.sh
[[ -f "${nix_sh}" ]] && source "${nix_sh}"
{%@@ endif @@%}
