#!/bin/bash

export SCRATCH=/scratch
export HOME1=/dftman/home1/ericb
export HOME2=/dftman/home2/ericb

if [[ "${HOSTNAME}" == "dellman5" ]]; then
    source "${HOME2}"/spack_dellman5/share/spack/setup-env.sh
else
    source "${HOME2}"/spack/share/spack/setup-env.sh
fi

if [[ "${HOSTNAME}" == "coreman4" ]]; then
    export PYENV_ROOT="${HOME2}/pyenv"
    [[ -d "${PYENV_ROOT}/bin" ]] && export PATH="${PYENV_ROOT}/bin:${PATH}"
    if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi
    if command -v pyenv-virtualenv-init 1>/dev/null 2>&1; then eval "$(pyenv virtualenv-init -)"; fi
fi

# TODO
# apt install libbz2-dev libffi-dev libreadline-dev libsqlite3-dev libssl-dev
# pyenv install 3.8.6
# pyenv global 3.8.6
# python -m pip install -U pip setuptools
# python -m pip install wheel
# python -m pip install ansible ansible-lint
# python -m pip install docker

if [ -f "${HOME}/.bashrc" ]; then
    source "${HOME}/.bashrc"
fi

export PATH="${HOME}/.cargo/bin:$PATH"

module use "${HOME}"/modules/coreman4
