#!/usr/bin/env bash

[[ $- == *i* ]] || return

if [[ $TERM == "alacritty" ]]; then
    export TERM=xterm-256color
fi

[[ -d "${PYENV_ROOT}/bin" ]] && export PATH="${PYENV_ROOT}/bin:${PATH}"
if command -v pyenv >/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi
if command -v pyenv-virtualenv-init 1>/dev/null 2>&1; then eval "$(pyenv virtualenv-init -)"; fi

source "${HOME}"/dotfiles/aliases.bash
source "${HOME}"/dotfiles/bash_hist.bash
source "${HOME}"/dotfiles/interactive_exports.bash
source "${HOME}"/dotfiles/functions.bash
