#!/usr/bin/env zsh

if [ -n "${__SOURCED_ZPROFILE}" ]; then return; fi
# echo "running zprofile"
export __SOURCED_ZPROFILE=1

if [[ "$TERM" != "" ]]; then
    stty -ixon
fi

uname=$(uname)

if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

if command -v rbenv >&/dev/null; then
    eval "$(rbenv init - --no-rehash zsh)"
fi
