#!/usr/bin/env zsh

# https://superuser.com/a/583502/551499
#
# This needs to live here and not in `~/.zprofile`; see that file for an
# explanation.
if [[ $(uname) == "Darwin" ]] && [[ -f /etc/zprofile ]]; then
    PATH=""
    . /etc/zprofile
fi

. "${HOME}"/dotfiles/path_exports.bash

# Put this early on, so that additions to $PATH take less precedence.
{%@@ if profile == "osmium" @@%}
# export ANACONDA_HOME="/home/eric/.conda"
export ANACONDA_HOME="/home/eric/.pyenv/versions/miniconda3-4.3.30"

export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
# export VIRTUALENVWRAPPER_VIRTUALENV=/usr/bin/virtualenv
export WORKON_HOME=$HOME/data/virtualenvs
{%@@ elif profile == "pop-os" @@%}
test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
{%@@ endif @@%}

[[ -d "${HOME}/.poetry/bin" ]] && export PATH="${HOME}/.poetry/bin:${PATH}"
# pyenv doesn't seem to be interfering with conda
[[ -d "${HOME}/.pyenv/bin" ]] && export PATH="${HOME}/.pyenv/bin:${PATH}"
if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi
if command -v pyenv-virtualenv-init 1>/dev/null 2>&1; then eval "$(pyenv virtualenv-init -)"; fi

if command -v rbenv 1>/dev/null 2>&1; then eval "$(rbenv init -)"; fi

if command -v jenv 1>/dev/null 2>&1; then eval "$(jenv init -)"; fi

[[ -f "${HOME}"/perl5/perlbrew/etc/bashrc ]] && . "${HOME}"/perl5/perlbrew/etc/bashrc

# Rust
[[ -f "${HOME}/.cargo/env" ]] && . "${HOME}/.cargo/env"

# Nim
[[ -d "${HOME}/.nimble/bin" ]] && export PATH="${HOME}/.nimble/bin:${PATH}"

# Node Version Manager
NVM_DIR="${HOME}/.nvm"
if [[ -d "${NVM_DIR}" ]]; then
    unset npm_config_prefix
    export NVM_DIR
    \. "${NVM_DIR}/nvm.sh"
    \. "${NVM_DIR}/bash_completion"
fi

# if [[ $(uname) == "Darwin" ]]; then
#     eval $(keychain --quiet --nogui --eval --inherit any --agents ssh id_rsa)
# else
#     eval $(keychain --quiet --nogui --eval --inherit any --systemd --agents ssh id_rsa)
# fi
eval $(keychain --quiet --nogui --eval --inherit any --agents ssh id_rsa)

# Spack
{%@@ if profile == "osmium" @@%}
. "${HOME}"/data/spack/share/spack/setup-env.sh
{%@@ elif profile == "pop-os" @@%}
. "${HOME}"/repositories/spack/share/spack/setup-env.sh
{%@@ endif @@%}
