#!/usr/bin/env zsh

source "${HOME}"/dotfiles/path_exports.bash

# export ANACONDA_HOME="/home/eric/.conda"
# TODO blergh
export ANACONDA_HOME="/home/eric/.pyenv/versions/miniconda3-4.7.12"

export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export WORKON_HOME="${HOME}"/data/virtualenvs

# All this stuff is here and not in .zshrc as is usually recommended so that
# *all* shells have access, not just interactive ones.

# These are...slow.
if command -v pyenv >/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi
if command -v pyenv-virtualenv-init >/dev/null 2>&1; then eval "$(pyenv virtualenv-init -)"; fi

hostname=$(hostname)

if [[ $hostname == "osmium" ]]; then
    export PRE_COMMIT_HOME="${HOME}"/data/.pre-commit
    export SPACK_ROOT="${HOME}"/data/spack
elif [[ $hostname == "scandium" ]]; then
    export PRE_COMMIT_HOME="${HOME}"/.cache/pre-commit
    export SPACK_ROOT="${HOME}"/repositories/spack
elif [[ $hostname == "sodium" ]]; then
    export PRE_COMMIT_HOME="${HOME}"/.cache/pre-commit
    export SPACK_ROOT="${HOME}"/repositories/spack
fi

[[ -d "${SPACK_ROOT}" ]] && source "${SPACK_ROOT}"/share/spack/setup-env.sh
