#!/usr/bin/env zsh

# autoload -U compinit && compinit

bindkey -e

# Changing Directories
unsetopt auto_cd
setopt auto_pushd

# Expansion and Globbing
unsetopt extended_glob
setopt nomatch

# Input/Output
setopt interactive_comments

# Job Control
unsetopt bg_nice
setopt long_list_jobs

# Prompting
setopt prompt_subst

# Zle
setopt beep
setopt emacs

# ???
setopt multios  # TODO I don't understand this
unsetopt notify
setopt pushd_ignore_dups

source "${HOME}"/dotfiles/berquist.zsh-theme
source "${HOME}"/dotfiles/history.zsh
source "${HOME}"/dotfiles/interactive_exports.bash
source "${HOME}"/dotfiles/aliases.bash
source "${HOME}"/dotfiles/functions.bash
source "${HOME}"/dotfiles/slurm.bash

hostname=$(hostname)

if [[ $hostname == "osmium" ]]; then
    source /usr/share/lmod/lmod/init/zsh
    module use "${HOME}/modules/osmium"
elif [[ $hostname == "sodium" ]]; then
    source "${HOME}"/dotfiles/aliases_macos.bash
fi

if command -v direnv >/dev/null 2>&1; then
    eval "$(direnv hook zsh)"
fi

source "${HOME}"/dotfiles/termsupport.zsh
source "${HOME}"/dotfiles/completion.zsh
