#!/usr/bin/env zsh

source "${HOME}/.zinit/bin/zinit.zsh"

autoload -Uz compaudit compinit

zinit for \
      OMZL::compfix.zsh \
      "${HOME}"/dotfiles/zcompdump.zsh \
      OMZL::completion.zsh \
      OMZL::git.zsh \
      OMZL::termsupport.zsh \
      OMZL::theme-and-appearance.zsh

zinit light romkatv/zsh-prompt-benchmark
zinit ice depth=1; zinit light sobolevn/wakatime-zsh-plugin
# Prompt
zinit ice svn
zinit snippet OMZP::git-prompt
zinit snippet "${HOME}"/dotfiles/berquist.zsh-theme
# Other
zinit ice svn
zinit snippet OMZP::gpg-agent

bindkey -e

unsetopt auto_cd
setopt auto_pushd
setopt beep
unsetopt extended_glob
setopt interactive_comments
setopt long_list_jobs
setopt multios  # TODO I don't understand this
setopt nomatch
unsetopt notify
setopt prompt_subst
setopt pushd_ignore_dups

zstyle :compinstall filename "${HOME}/.zshrc"
autoload -Uz compinit
compinit

source "${HOME}"/dotfiles/history.zsh
source "${HOME}"/dotfiles/interactive_exports.bash
source "${HOME}"/dotfiles/aliases.bash
source "${HOME}"/dotfiles/functions.bash
# source "${HOME}"/dotfiles/slurm.bash

{%@@ if profile == "osmium" @@%}
# re-export
export QCPROGS="${HOME}/data/opt/apps"
export apps="${QCPROGS}"

source /usr/bin/virtualenvwrapper.sh

source /usr/share/lmod/lmod/init/zsh
module use "${HOME}/modules/osmium"
{%@@ elif profile == "sodium.local" @@%}
source "${HOME}"/dotfiles/aliases_macos.bash
{%@@ endif @@%}

eval "$(direnv hook zsh)"
