config:
  banner: false
  dotpath: dotfiles
  link_dotfile_default: link
  link_on_import: link
  showdiff: true
dotfiles:
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_emacs.d:
    src: emacs.d
    dst: ~/.emacs.d
  d_idea:
    src: idea
    dst: ~/.idea
  d_tmux:
    src: tmux
    dst: ~/.tmux
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_ansible.cfg:
    src: ansible.cfg
    dst: ~/.ansible.cfg
  f_aspell.en.prepl:
    src: aspell.en.prepl
    dst: ~/.aspell.en.prepl
  f_aspell.en.pws:
    src: aspell.en.pws
    dst: ~/.aspell.en.pws
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_clisprc.lisp:
    src: clisprc.lisp
    dst: ~/.clisprc.lisp
  f_compton.conf:
    src: compton.conf
    dst: ~/.compton.conf
  f_condarc:
    src: condarc
    dst: ~/.condarc
  f_cuby4:
    src: cuby4
    dst: ~/.cuby4
  f_dconf.nix:
    src: config/nixpkgs/dconf.nix
    dst: ~/.config/nixpkgs/dconf.nix
  f_direnvrc:
    src: config/direnv/direnvrc
    dst: ~/.config/direnv/direnvrc
  f_emacsclient.desktop:
    src: local/share/applications/emacsclient.desktop
    dst: ~/.local/share/applications/emacsclient.desktop
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_gnome-keyring-ssh.desktop:
    src: config/autostart/gnome-keyring-ssh.desktop
    dst: ~/.config/autostart/gnome-keyring-ssh.desktop
  f_gpg-agent.conf:
    src: gnupg/gpg-agent.conf
    dst: ~/.gnupg/gpg-agent.conf
  f_gpg.conf:
    src: gnupg/gpg.conf
    dst: ~/.gnupg/gpg.conf
  f_home.nix:
    src: config/nixpkgs/home.nix
    dst: ~/.config/nixpkgs/home.nix
  f_i3_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_i3status_config:
    src: config/i3status/config
    dst: ~/.config/i3status/config
  f_mdlrc:
    src: mdlrc
    dst: ~/.mdlrc
  f_nanorc:
    src: nanorc
    dst: ~/.nanorc
  f_nitrogen.cfg:
    src: config/nitrogen/nitrogen.cfg
    dst: ~/.config/nitrogen/nitrogen.cfg
  f_nitrogen_bg-saved.cfg:
    src: config/nitrogen/bg-saved.cfg
    dst: ~/.config/nitrogen/bg-saved.cfg
  f_nixpkgs_overlays_discord.nix:
    src: config/nixpkgs/overlays/discord.nix
    dst: ~/.config/nixpkgs/overlays/discord.nix
  f_nvimrc:
    src: nvimrc
    dst: ~/.nvimrc
  f_override.conf:
    src: config/systemd/user/emacs.service.d/override.conf
    dst: ~/.config/systemd/user/emacs.service.d/override.conf
  f_pdbrc:
    src: pdbrc
    dst: ~/.pdbrc
  f_pylintrc:
    src: pylintrc
    dst: ~/.pylintrc
  f_rc:
    src: ssh/rc
    dst: ~/.ssh/rc
  f_sbclrc:
    src: sbclrc
    dst: ~/.sbclrc
  f_terminalrc:
    src: config/xfce4/terminal/terminalrc
    dst: ~/.config/xfce4/terminal/terminalrc
  f_terminalrc.osmium:
    src: config/xfce4/terminal/terminalrc.osmium
    dst: ~/.config/xfce4/terminal/terminalrc.osmium
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_user.json:
    src: config/exercism/user.json
    dst: ~/.config/exercism/user.json
  f_vmdrc:
    src: vmdrc
    dst: ~/.vmdrc
  f_xdefaults:
    src: Xdefaults
    dst: ~/.Xdefaults
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
profiles:
  beryllium:
    dotfiles:
    - d_bat
    - d_emacs.d
    - d_tmux
    - f_alacritty.yml
    - f_ansible.cfg
    - f_aspell.en.prepl
    - f_aspell.en.pws
    - f_condarc
    - f_gitconfig
    - f_gitignore
    - f_gnome-keyring-ssh.desktop
    - f_gpg-agent.conf
    - f_gpg.conf
    - f_mdlrc
    - f_tmux.conf
    - f_zprofile
    - f_zshenv
    - f_zshrc
  coreman4:
    dotfiles:
    - d_bat
    - d_emacs.d
    - d_tmux
    - f_ansible.cfg
    - f_bash_profile
    - f_bashrc
    - f_gitconfig
    - f_gitignore
    - f_gnome-keyring-ssh.desktop
    - f_gpg-agent.conf
    - f_gpg.conf
    - f_tmux.conf
  osmium:
    dotfiles:
    - d_bat
    - d_emacs.d
    - d_idea
    - d_tmux
    - f_alacritty.yml
    - f_ansible.cfg
    - f_aspell.en.prepl
    - f_aspell.en.pws
    - f_clisprc.lisp
    - f_compton.conf
    - f_condarc
    - f_cuby4
    - f_direnvrc
    - f_emacsclient.desktop
    - f_gitconfig
    - f_gitignore
    - f_gnome-keyring-ssh.desktop
    - f_gpg-agent.conf
    - f_gpg.conf
    - f_mdlrc
    - f_nanorc
    - f_nvimrc
    - f_override.conf
    - f_pdbrc
    - f_pylintrc
    - f_sbclrc
    - f_terminalrc
    - f_terminalrc.osmium
    - f_tmux.conf
    - f_user.json
    - f_vmdrc
    - f_xinitrc
    - f_zprofile
    - f_zshenv
    - f_zshrc
  scandium:
    dotfiles:
    - d_bat
    - d_emacs.d
    - d_tmux
    - f_alacritty.yml
    - f_ansible.cfg
    - f_aspell.en.prepl
    - f_aspell.en.pws
    - f_condarc
    - f_dconf.nix
    - f_gitconfig
    - f_gitignore
    # - f_gpg-agent.conf
    # - f_gpg.conf
    - f_home.nix
    - f_mdlrc
    # - f_nanorc
    - f_nixpkgs_overlays_discord.nix
    # - f_sbclrc
    - f_tmux.conf
    - f_user.json
    # - f_xdefaults
    - f_zprofile
    - f_zshenv
    - f_zshrc
  sodium.local:
    dotfiles:
    - d_bat
    - d_emacs.d
    - d_tmux
    - f_aspell.en.prepl
    - f_aspell.en.pws
    - f_condarc
    - f_gitconfig
    - f_gitignore
    - f_mdlrc
    - f_nanorc
    - f_tmux.conf
    - f_zprofile
    - f_zshenv
    - f_zshrc
