---
- name: install GitHub repos
  gather_facts: false
  hosts: localhost
  vars_files:
    - package_lists.yaml
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    base_dir: "{{ home_dir }}/repositories"
    fonts_dir: "{{ home_dir }}/.local/share/fonts"
  pre_tasks:
    - setup:
        filter: ansible_system
  tasks:
    - name: ensure base exists
      file:
        path: "{{ base_dir }}"
        state: directory
    - name: get repos from GitHub
      git:
        repo: "https://github.com/{{ item }}.git"
        dest: "{{ base_dir }}/{{ item.split('/')[1] }}"
      loop: "{{ default_github_repos }}"
    - name: make sure fonts dir exists
      file:
        path: "{{ fonts_dir }}"
        state: directory
      when: ansible_system == "Linux"
    - name: link codeface into fonts dir
      file:
        src: "{{ base_dir }}/codeface"
        dest: "{{ fonts_dir }}/codeface"
        state: link
      when: ansible_system == "Linux"
    - name: update font cache
      command: fc-cache
      when: ansible_system == "Linux"
