---
- name: install GitHub repos
  gather_facts: false
  hosts: localhost
  vars_files:
    - package_lists.yaml
  vars:
    # TODO
    base_dir: /home/eric/repositories
  tasks:
    - name: ensure base exists
      file:
        path: "{{ base_dir }}"
        state: directory
    - name: get repos from GitHub
      git:
        repo: "https://github.com/{{ item }}.git"
        # TODO
        dest: "{{ base_dir }}/{{ item | split('/') | last }}"
    - name: make sure fonts dir exists
      file:
        path: /home/eric/.local/share/fonts
        state: directory
      # TODO only when Linux
    - name: link codeface into fonts dir
      file:
        src: "{{ base_dir }}/codeface"
        dest: /home/eric/.local/share/fonts/codeface
        state: link
      # TODO only when Linux
    - name: update font cache
      command: fc-cache
      # TODO only when Linux
