(eval-when-compile
  (require 'color-theme))

(defun color-theme-ejb01 ()
  (interactive)
  (color-theme-install
   '(ejb-custom-01
     ((background-color . "#1d2c33")
      (background-mode . light)
      (border-color . "#111122")
      (cursor-color . "#fce94f")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#111122"))))
     (mode-line ((t (:foreground "#ffffff" :background "#595959"))))
     (region ((t (:background "#0d2545"))))
     (font-lock-builtin-face ((t (:foreground "#2486f0"))))
     (font-lock-comment-face ((t (:foreground "#2961c2"))))
     (font-lock-function-name-face ((t (:foreground "#00eda3"))))
     (font-lock-keyword-face ((t (:foreground "#2c71af"))))
     (font-lock-string-face ((t (:foreground "#29c0ff"))))
     (font-lock-type-face ((t (:foreground"#8ae234"))))
     (font-lock-constant-face ((t (:foreground "#0fe65b"))))
     (font-lock-variable-name-face ((t (:foreground "#8737f6"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-ejb01)

(defun color-theme-example ()
  "Example theme. Carbon copy of color-theme-gnome contributed by Jonadab."
  (interactive)
  (color-theme-install
   '(color-theme-example
     ((foreground-color . "wheat")
      (background-color . "darkslategrey")
      (background-mode . dark))
     (default ((t (nil))))
     (region ((t (:foreground "cyan" :background "dark cyan"))))
     (underline ((t (:foreground "yellow" :underline t))))
     (modeline ((t (:foreground "dark cyan" :background "wheat"))))
     (modeline-buffer-id ((t (:foreground "dark cyan" :background "wheat"))))
     (modeline-mousable ((t (:foreground "dark cyan" :background "wheat"))))
     (modeline-mousable-minor-mode ((t (:foreground "dark cyan" :background "wheat"))))
     (italic ((t (:foreground "dark red" :italic t))))
     (bold-italic ((t (:foreground "dark red" :bold t :italic t))))
     (font-lock-comment-face ((t (:foreground "Firebrick"))))
     (bold ((t (:bold)))))))

(defun sweyla753129 ()
  (interactive)
  (color-theme-install
   '(sweyla753129
      ((background-color . "#000800")
      (background-mode . light)
      (border-color . "#323232")
      (cursor-color . "#ffffff")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#323232"))))
     (mode-line ((t (:foreground "#ffffff" :background "#323232"))))
     (region ((t (:background "#323232"))))
     (font-lock-builtin-face ((t (:foreground "#2afcff"))))
     (font-lock-comment-face ((t (:foreground "#57fffe"))))
     (font-lock-function-name-face ((t (:foreground "#c1adff"))))
     (font-lock-keyword-face ((t (:foreground "#13ebff"))))
     (font-lock-string-face ((t (:foreground "#36ffb9"))))
     (font-lock-type-face ((t (:foreground"#ffffff"))))
     (font-lock-constant-face ((t (:foreground "#05f3de"))))
     (font-lock-variable-name-face ((t (:foreground "#086ce5"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'sweyla753129)

(defun sweyla802975 ()
  (interactive)
  (color-theme-install
   '(sweyla802975
      ((background-color . "#000203")
      (background-mode . light)
      (border-color . "#323232")
      (cursor-color . "#ffffff")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#323232"))))
     (mode-line ((t (:foreground "#ffffff" :background "#323232"))))
     (region ((t (:background "#323232"))))
     (font-lock-builtin-face ((t (:foreground "#2a6e8e"))))
     (font-lock-comment-face ((t (:foreground "#9719ea"))))
     (font-lock-function-name-face ((t (:foreground "#3b00ff"))))
     (font-lock-keyword-face ((t (:foreground "#00599c"))))
     (font-lock-string-face ((t (:foreground "#6900bf"))))
     (font-lock-type-face ((t (:foreground"#ffffff"))))
     (font-lock-constant-face ((t (:foreground "#cd2de4"))))
     (font-lock-variable-name-face ((t (:foreground "#c70dff"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'sweyla802975)

(defun standard-dark ()
  (interactive)
  (color-theme-install
   '(standard-dark
      ((background-color . "#101e2e")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (region ((t (:background "#0d4519"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-function-name-face ((t (:foreground "#edd400"))))
     (font-lock-keyword-face ((t (:foreground "#729fcf"))))
     (font-lock-string-face ((t (:foreground "#ad7fa8"))))
     (font-lock-type-face ((t (:foreground"#8ae234"))))
     (font-lock-constant-face ((t (:foreground "#eeeeec"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'standard-dark)
