[colors.bright]
black = "#b4b4b4"
blue = "#8ac6f2"
cyan = "#70cecc"
green = "#95e454"
magenta = "#f6b3df"
red = "#e5786d"
white = "#ffffff"
yellow = "#e7e784"

[colors.normal]
black = "#000000"
blue = "#5b98c2"
cyan = "#00b7eb"
green = "#4bc98a"
magenta = "#663399"
red = "#b85149"
white = "#f6f3e8"
yellow = "#cae682"

[colors.primary]
background = "#242424"
foreground = "#e5e1d8"

[env]
TERM = "xterm-256color"

[font.bold]
family = "Panic Sans"

[font.italic]
family = "Panic Sans"

[font.normal]
family = "Panic Sans"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[window]
option_as_alt = "OnlyLeft"
