#!/usr/bin/env bash

# Commands to run that act on tmux when inside tmux.
#
# Idea stolen from
# https://github.com/zenfailure/dotfiles/blob/715bbe81c3250a0d121f560a42cdabd6d51b60df/tmux/tmux.4/tmux/runner

set -euo pipefail

# Update the current session's environment variables with those from the outer
# environment. Useful for when the SSH socket keeps changing, among other
# things.
update_env() {
    current_session="$(tmux display-message -p "#S")"
    echo ${current_session}
    while read line; do
        if [[ ${line:0:1} == "-" ]]; then
            echo "export ${line:1}="
        else
            echo "export ${line}"
        fi
    done <<< $(tmux show-environment -t ${current_session})
}

main() {
    command="$1"
    shift
    $command "$@"
    exit 0
}

main "$@"
