---
- name: get current dconf value
  command: "gsettings get {{ dconf_setting_triple[0] }} {{ dconf_setting_triple[1] }}"
  changed_when: false
  register: gsettings_get

- name: apply dconf value if not already set
  command: "gsettings set {{ dconf_setting_triple[0] }} {{ dconf_setting_triple[1] }} {{ dconf_setting_triple[2] }}"
  register: gsettings_set
  # GNOME is bad
  failed_when: '"WARNING" in gsettings_set.stderr'
  when:
    - gsettings_get.stdout != dconf_setting_triple[2]
