- name: install Docker on Debian-based systems
  hosts: all
  vars:
    apt_https_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tasks:
    - name: prepare apt to use a repository over HTTPS
      apt:
        name: "{{ apt_https_packages }}"
        update_cache: true
        install_recommends: false
    - name: get Docker Ubuntu repository signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: add Docker Ubuntu repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    - name: install Docker
      apt:
        name: "{{ docker_packages }}"
        update_cache: true
        install_recommends: false
    - name: start Docker daemon on boot
      systemd:
        name: docker
        enabled: true
    # sudo usermod -aG docker ericb
    # - name: add me to Docker group
