---
- name: install Rust
  # curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  gather_facts: false
  hosts: all
  pre_tasks:
    - setup:
        gather_subset:
          - system
  tasks:
    - name: get rustup installer
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/install_rustup.bash
    - name: run rustup
      command:
        cmd: bash /tmp/install_rustup.bash -y --profile=complete --no-modify-path
        creates: ~/.rustup/settings.toml
    - name: add rust-analyzer as component
      command:
        cmd: rustup component add rust-analyzer
        creates: ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rust-analyzer
      when: ansible_system == "Linux"

- name: install Nim
  # curl https://nim-lang.org/choosenim/init.sh -sSf | sh
  gather_facts: false
  hosts: all
  vars:
    choosenim_location: ~/.nimble/bin/choosenim
  tasks:
    - name: get choosenim installer
      get_url:
        url: https://nim-lang.org/choosenim/init.sh
        dest: /tmp/install_choosenim.bash
    - name: install choosenim
      command:
        cmd: bash /tmp/install_choosenim.bash -y
        creates: "{{ choosenim_location }}"
    - name: install latest stable Nim
      command: "{{ choosenim_location }} update stable"
      register: choosenim_update_stable
      changed_when: "'Already up to date at version' not in choosenim_update_stable.stdout"

- name: install Julia packages
  gather_facts: false
  hosts: all
  tasks:
    - name: check for Julia
      shell: "$(command -v julia)"
      register: julia_result
    - name: install base environment packages
      command:
        cmd: julia 'using Pkg; Pkg.add(["LanguageServer"]); Pkg.instantiate()'
      when: julia_result.rc == 0
