---
- name: install GitHub repos
  gather_facts: false
  hosts: all
  vars_files:
    - common_vars.yaml
    - package_lists.yaml
  vars:
    fonts_dir: "{{ home_dir }}/.local/share/fonts"
  pre_tasks:
    - setup:
        gather_subset:
          - distribution
          - system
  tasks:
    - name: ensure base exists
      file:
        path: "{{ base_dir }}"
        state: directory
    - name: get repos from GitHub
      git:
        repo: "https://github.com/{{ item }}.git"
        dest: "{{ base_dir }}/{{ item.split('/')[1] }}"
      loop: "{{ default_github_repos }}"
    - name: make sure fonts dir exists
      file:
        path: "{{ fonts_dir }}"
        state: directory
      when: ansible_system == "Linux"
    - name: link codeface into fonts dir
      file:
        src: "{{ base_dir }}/codeface"
        dest: "{{ fonts_dir }}/codeface"
        state: link
      when: ansible_system == "Linux"
    - name: update font cache
      command: fc-cache
      when: ansible_system == "Linux"
    - name: link chemacs
      file:
        src: "{{ base_dir }}/chemacs/.emacs"
        dest: "{{ home_dir }}/.emacs"
        state: link
    - name: clone oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: "{{ home_dir }}/.oh-my-zsh"
    - name: ensure zinit prefix exists
      file:
        path: "{{ home_dir }}/.zinit"
        state: directory
    - name: clone zinit
      git:
        repo: https://github.com/zdharma/zinit.git
        dest: "{{ home_dir }}/.zinit/bin"
    - name: ensure pyenv prefix exists
      file:
        path: "{{ home_dir }}/.pyenv"
        state: directory
    - name: install pyenv, but not on Arch or macOS
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: "{{ home_dir }}/.pyenv"
      when: ansible_distribution != "Archlinux"
