---
- name: install packages for Debian derivatives
  gather_facts: false
  hosts: all
  vars:
    eza_unpack_dir: /tmp/eza
    eza_version: 0.11
  vars_files:
    - package_lists.yaml
  pre_tasks:
    - setup:
        gather_subset:
          - distribution
      tags:
        - always
  tasks:
    - name: add Emacs snapshot repository
      apt_repository:
        repo: "ppa:ubuntu-elisp/ppa"
      when: ansible_distribution in ("Ubuntu", "Pop!_OS")
    - name: install packages for Pop!_OS
      apt:
        name: "{{ default_packages_popos }}"
      when: ansible_distribution == "Pop!_OS"
    - name: install packages for Ubuntu
      apt:
        name: "{{ default_packages_ubuntu }}"
      when: ansible_distribution == "Ubuntu"
    # - name: prepare apt to use a repository over HTTPS
    #   apt:
    #     name: "{{ apt_https_packages }}"
    #     update_cache: true
    #     install_recommends: false
    #   when: ansible_distribution in ("Ubuntu", "Pop!_OS")
    - name: install archives for Ubuntu or Pop!_OS
      apt:
        deb: "{{ item }}"
      loop: "{{ default_packages_deb }}"
      when: ansible_distribution in ("Ubuntu", "Pop!_OS")
    - name: make eza unpack dir
      file:
        path: "{{ eza_unpack_dir }}"
        state: directory
      when: ansible_distribution in ("Ubuntu", "Pop!_OS")
      tags:
        - eza
    - name: get eza archive and unzip
      unarchive:
        src: "https://github.com/eza-community/eza/releases/download/v{{ eza_version }}/eza-linux-x86_64-v{{ eza_version }}.zip"
        dest: "{{ eza_unpack_dir }}"
        remote_src: true
      when: ansible_distribution in ("Ubuntu", "Pop!_OS")
      tags:
        - eza
    - name: move eza files into place
      copy:
        src: "{{ item['src'] }}"
        dest: "{{ item['dest'] }}"
        remote_src: true
      loop:
        # yamllint disable rule:braces
        - { src: "{{ eza_unpack_dir }}/bin/eza", dest: /usr/local/bin/eza }
        - { src: "{{ eza_unpack_dir }}/completions/eza.bash", dest: /etc/bash_completion.d/eza.bash }
        - { src: "{{ eza_unpack_dir }}/completions/eza.fish", dest: /usr/share/fish/vendor_completions.d/eza.fish }
        - { src: "{{ eza_unpack_dir }}/completions/eza.zsh", dest: /usr/local/share/zsh/site-functions/eza.zsh }
        - { src: "{{ eza_unpack_dir }}/man/eza.1", dest: /usr/local/man/eza.1 }
        - { src: "{{ eza_unpack_dir }}/man/eza_colors.5", dest: /usr/local/man/eza_colors.5 }
        # yamllint enable rule:braces
      when: ansible_distribution in ("Ubuntu", "Pop!_OS")
      tags:
        - eza
