---
# https://zulip.com/help/desktop-app-install-guide
#
# sudo apt-key adv --keyserver pool.sks-keyservers.net --recv 69AD12704E71A4803DCA3A682424BE5AE9BD10D9
# echo "deb https://dl.bintray.com/zulip/debian/ stable main" | sudo tee -a /etc/apt/sources.list.d/zulip.list
# sudo apt update
# sudo apt install zulip
- name: install Zulip on Ubuntu-based systems
  gather_facts: false
  hosts: all
  pre_tasks:
    - setup:
        gather_subset:
          - distribution
      tags:
        - always
  tasks:
    - name: add Zulip repository key
      apt_key:
        keyserver: pool.sks-keyservers.net
        id: 2424BE5AE9BD10D9
        # id: 69AD12704E71A4803DCA3A682424BE5AE9BD10D9
      when: ansible_distribution in ("Ubuntu", "Pop!_OS")
    - name: add Zulip repository
      apt_repository:
        repo: "deb https://dl.bintray.com/zulip/debian/ stable main"
      when: ansible_distribution in ("Ubuntu", "Pop!_OS")
    - name: install Zulip
      apt:
        name: zulip
        update_cache: true
      when: ansible_distribution in ("Ubuntu", "Pop!_OS")
