---
# These have logic that works standalone.
- import_playbook: install_anaconda.yaml
- import_playbook: install_github_repos.yaml
- import_playbook: install_languages.yaml

- name: deploy dotfiles
  hosts: localhost
  gather_facts: false
  vars:
    dotdrop_manual_install_file: ~/dotfiles/dotdrop/dotdrop.sh
    dotdrop_public_config: ~/dotfiles/config.yaml
    dotdrop_private_config: ~/dotfiles/dotfiles-private/config.yaml
  pre_tasks:
    - setup:
        gather_subset:
          - distribution
          - system
  tasks:
    - name: install dotdrop dependencies
      command: python3 -m pip install --user -r ~/dotfiles/dotdrop/requirements.txt
      register: pip_install
      changed_when: "'Successfully installed' in pip_install.stdout"
      when: ansible_distribution != "Archlinux"
    - name: bootstrap dotdrop
      command: ~/dotfiles/dotdrop/bootstrap.sh
      args:
        creates: "{{ dotdrop_manual_install_file }}"
      when: ansible_distribution != "Archlinux"
    - name: deploy from public dotfiles on Arch
      command: "dotdrop install -c {{ dotdrop_public_config }}"
      when: ansible_distribution == "Archlinux"
    - name: deploy from public dotfiles not on Arch
      command: "{{ dotdrop_manual_install_file }} install -c {{ dotdrop_public_config }}"
      register: deploy_public_notarch
      changed_when: "'0 dotfile(s) installed.' not in deploy_public_notarch.stdout"
      when: ansible_distribution != "Archlinux"
    - name: deploy from private dotfiles on Arch
      command: "dotdrop install -c {{ dotdrop_private_config }}"
      when: ansible_distribution == "Archlinux"
    - name: deploy from private dotfiles not on Arch
      command: "{{ dotdrop_manual_install_file }} install -c {{ dotdrop_private_config }}"
      register: deploy_private_notarch
      changed_when: "'0 dotfile(s) installed.' not in deploy_private_notarch.stdout"
      when: ansible_distribution != "Archlinux"

- name: enable and start services
  gather_facts: false
  hosts: localhost
  pre_tasks:
    - setup:
        gather_subset:
          - distribution
          - system
  tasks:
    - name: enable and start Dropbox
      systemd:
        name: dropbox
        state: started
        enabled: true
        scope: user
      when: ansible_distribution == "Archlinux"
    - name: enable and start Emacs daemon
      systemd:
        name: emacs
        state: started
        enabled: true
        scope: user
      when: ansible_system == "Linux"
