---
- name: install packages for Arch Linux
  gather_facts: false
  hosts: all
  vars_files:
    - package_lists.yaml
  tasks:
    - name: install packages
      pacman:
        name: "{{ default_arch_packages }}"
      # For debugging
      # pacman:
      #   name: "{{ item }}"
      # loop: "{{ default_arch_packages }}"
