---
- name: install packages for Debian derivatives
  gather_facts: false
  hosts: all
  vars_files:
    - package_lists.yaml
  pre_tasks:
    - setup:
        gather_subset:
          - distribution
  tasks:
    - name: add Emacs snapshot repository
      apt_repository:
        repo: "ppa:ubuntu-elisp/ppa"
      when: ansible_distribution == "Pop!_OS" or ansible_distribution == "Ubuntu"
    - name: install packages for Pop!_OS
      apt:
        name: "{{ default_packages_popos }}"
      when: ansible_distribution == "Pop!_OS"
    - name: install packages for Ubuntu
      apt:
        name: "{{ default_packages_ubuntu }}"
      when: ansible_distribution == "Ubuntu"
