---
- name: set the shell to zshell
  gather_facts: false
  hosts: all
  vars_files:
    - common_vars.yaml
  pre_tasks:
    - setup:
        gather_subset:
          - system
      tags:
        - always
  tasks:
    - name: set the shell to zshell on Linux
      command: "chsh -s /bin/zsh {{ username }}"
      when: ansible_system == "Linux"
    # TODO make sure this is in /etc/shells on macOS
    - name: set the shell to zshell on macOS
      command: "chsh -s /usr/local/bin/zsh {{ username }}"
      when: ansible_system != "Linux"
