---
- name: set the shell to zshell
  gather_facts: false
  hosts: all
  pre_tasks:
    - setup:
        gather_subset:
          - system
      tags:
        - always
  tasks:
    - name: set the shell to zshell on Linux
      command: "chsh -s /bin/zsh {{ lookup('env', 'USER') }}"
      when: ansible_system == "Linux"
    - name: check that /usr/local/bin/zsh is available in /etc/shells
      command: "grep -F '/usr/local/bin/zsh' /etc/shells"
      register: custom_zsh_available
      when: ansible_system == "macOS"
    - name: set the shell to zshell on macOS
      command: "chsh -s /usr/local/bin/zsh {{ lookup('env', 'USER') }}"
      when:
        - ansible_system == "macOS"
        - custom_zsh_available.rc == 0
